import 'package:flutter/material.dart';
import 'package:petapp/models/pet_model.dart';

List<String> petCategories = const [
  "Dog",
  "Cat",
  "Rabbit",
  "Birds",
  "Fishes",
  
];

List<PetModel> listOfPetsGeneral = [
  PetModel(
    id: 'pet_001',
    imageUrl: 'assets/images/pet1.jpg',
    age: 23,
    name: "Bella",
    price: 1500,
    description: "A cute and friendly dog who has been trained well.",
    breed: "Golden Retriever",
    weight: 20.5,
    location: "Birmingham, London",
    petType: "Dog",
    adopted: false,
    time: null,
  ),
  PetModel(
    id: 'pet_002',
    imageUrl: 'assets/images/pet2.jpg',
    age: 23,
    name: "Whiskers",
    price: 2200,
    description: "A lovely cat who enjoys sunny spots.",
    breed: "Persian",
    weight: 4.3,
    location: "Manchester, UK",
    petType: "Cat",
    adopted: false,
    time: null,
  ),
  PetModel(
    id: 'pet_003',
    imageUrl: 'assets/images/pet3.jpg',
    age: 2,
    name: "Fluffy",
    price: 50,
    description: "A small, friendly rabbit perfect for families.",
    breed: "Angora",
    weight: 1.2,
    location: "Leeds, UK",
    petType: "Dog",
    adopted: false,
    time: null,
  ),
  PetModel(
    id: 'pet_004',
    imageUrl: 'assets/images/pet4.jpg',
    age: 1,
    name: "Tweety",
    price: 30,
    description: "A colorful bird with a cheerful song.",
    breed: "Canary",
    weight: 0.2,
    location: "Glasgow, UK",
    petType: "Dog",
    adopted: false,
    time: null,
  ),
  PetModel(
    id: 'pet_005',
    imageUrl: 'assets/images/pet5.jpg',
    age: 3,
    name: "Splash",
    price: 15,
    description: "A beautiful goldfish that adds color to any tank.",
    breed: "Goldfish",
    weight: 0.1,
    location: "London, UK",
    petType: "Dog",
    adopted: false,
    time: null,
  ),
  PetModel(
    id: 'pet_006',
    imageUrl: 'assets/images/pet6.jpg',
    age: 23,
    name: "Daisy",
    price: 1900,
    description: "A cute and friendly dog.",
    breed: "Pomeranian",
    weight: 10.5,
    location: "Brighton, UK",
    petType: "Birds",
    adopted: false,
    time: null,
  ),
  PetModel(
    id: 'pet_007',
    imageUrl: 'assets/images/pet7.jpg',
    age: 23,
    name: "Bailey",
    price: 2300,
    description: "A trained and protective dog.",
    breed: "German Shepherd",
    weight: 30.0,
    location: "Sheffield, UK",
    petType: "Rabbit",
    adopted: false,
    time: null,
  ),
  PetModel(
    id: 'pet_008',
    imageUrl: 'assets/images/pet8.jpg',
    age: 23,
    name: "Lucy",
    price: 1750,
    description: "A friendly dog with lots of energy.",
    breed: "Husky",
    weight: 27.0,
    location: "Edinburgh, UK",
    petType: "Cat",
    adopted: false,
    time: null,
  ),
  PetModel(
    id: 'pet_009',
    imageUrl: 'assets/images/pet9.jpg',
    age: 23,
    name: "Rocky",
    price: 2400,
    description: "A charming dog with a unique coat pattern.",
    breed: "Dalmatian",
    weight: 25.0,
    location: "Glasgow, UK",
    petType: "Dog",
    adopted: false,
    time: null,
  ),
  PetModel(
    id: 'pet_010',
    imageUrl: 'assets/images/pet11.jpg',
    age: 23,
    name: "Cooper",
    price: 2000,
    description: "A cute and friendly dog.",
    breed: "Shih Tzu",
    weight: 12.0,
    location: "London, UK",
    petType: "Dog",
    adopted: false,
    time: null,
  ),
  PetModel(
    id: 'pet_011',
    imageUrl: 'assets/images/pet12.jpg',
    age: 23,
    name: "Sadie",
    price: 1550,
    description: "A lovable dog with a playful spirit.",
    breed: "Siberian Husky",
    weight: 22.0,
    location: "Dublin, Ireland",
    petType: "Dog",
    adopted: false,
    time: null,
  ),
  PetModel(
    id: 'pet_012',
    imageUrl: 'assets/images/pet13.jpg',
    age: 23,
    name: "Zoe",
    price: 2250,
    description: "A well-trained dog with a friendly nature.",
    breed: "French Bulldog",
    weight: 14.0,
    location: "Belfast, UK",
    petType: "Rabbit",
    adopted: false,
    time: null,
  ),
  PetModel(
    id: 'pet_013',
    imageUrl: 'assets/images/pet14.jpg',
    age: 23,
    name: "Chloe",
    price: 1700,
    description: "A cute and friendly dog.",
    breed: "Chihuahua",
    weight: 6.0,
    location: "Cardiff, UK",
    petType: "Fishes",
    adopted: false,
    time: null,
  ),
  PetModel(
    id: 'pet_014',
    imageUrl: 'assets/images/pet15.jpg',
    age: 23,
    name: "Teddy",
    price: 1600,
    description: "A fluffy and lovable dog.",
    breed: "Maltese",
    weight: 7.0,
    location: "Oxford, UK",
    petType: "Fishes",
    adopted: false,
    time: null,
  ),
  PetModel(
    id: 'pet_015',
    imageUrl: 'assets/images/pet16.jpg',
    age: 23,
    name: "Buster",
    price: 1950,
    description: "A cute and friendly dog.",
    breed: "Boxer",
    weight: 24.0,
    location: "Cambridge, UK",
    petType: "Cat",
    adopted: false,
    time: null,
  ),
  PetModel(
    id: 'pet_016',
    imageUrl: 'assets/images/pet17.jpg',
    age: 23,
    name: "Riley",
    price: 2050,
    description: "A cute and friendly dog.",
    breed: "Akita",
    weight: 28.0,
    location: "Bath, UK",
    petType: "Cat",
    adopted: false,
    time: null,
  ),
  PetModel(
    id: 'pet_017',
    imageUrl: 'assets/images/pet18.jpg',
    age: 23,
    name: "Sophie",
    price: 1850,
    description: "A cute and friendly dog.",
    breed: "Pug",
    weight: 10.0,
    location: "Newcastle, UK",
    petType: "Birds",
    adopted: false,
    time: null,
  ),
];

List<String> detailsInHorizontal = ["Age", "Breed", "Weight"];

List<String> categoryimages = [
  'assets/images/no_bg/dog_nobg.png',
  'assets/images/no_bg/cat_nobg.png',
  'assets/images/no_bg/rabbit_nobg.png',
  'assets/images/no_bg/parrot_nobg.png',
  'assets/images/no_bg/fish_nobg.png',
  'assets/images/no_bg/turt_nobg.png',
  'assets/images/no_bg/hamster_nobg.png',
  'assets/images/no_bg/gp_nobg.png',
];

List<Icon> listOfIcons = const [
  Icon(Icons.person),
  Icon(Icons.location_city_outlined),
  Icon(Icons.payment),
  Icon(Icons.list_outlined),
  Icon(Icons.wallet),
  Icon(Icons.settings),
  Icon(Icons.help),
];

List<String> listOfIconLabels = [
  "My profile",
  "Manage Address",
  "Payment methods",
  "My orders",
  "My wallet",
  "Settings",
  "Help center"
];
